### ISSUE TITLE
常用連結區

### ISSUE THREAD

**Issue by RexYuan** [communityNTNU/surviveNTNU#12]
1. [師大首頁](http://www3.ntnu.edu.tw/)
2. [選課首頁](http://www.ntnu.edu.tw/aa/courseweb.html)
3. [圖書館首頁](http://www.lib.ntnu.edu.tw/)
4. [師大信箱首頁](https://webmail.ntnu.edu.tw/cgi-bin/owmmdir2/openwebmail.pl)
5. [校務行政系統](http://iportal.ntnu.edu.tw/ntnu/)
6. [Moodle](http://moodle2.ntnu.edu.tw/)
7. [Moodle2]()

還有什麼？

**Comment by wi1d5ky** [comment]
moodle2
2015/9/20 下午5:50於 "RexYuan" <notifications@github.com>寫道：

**Comment by wildskyf** [comment]
moodle 和 moodle2 還沒統一，所以可能都要放…

學校到底在幹麻 = =

**Comment by RexYuan** [comment]
同意，之後任何人有提議請直接加進列表吧！
