### ISSUE TITLE
YouBike 跟公車資訊

### ISSUE THREAD

**Issue by RexYuan** [communityNTNU/surviveNTNU#14]
- [YouBike臺北市公共自行車即時資訊](http://data.taipei/opendata/datalist/datasetMeta?oid=8ef1626a-892a-4218-8344-f7ac46e1aa48)
- [公車動態資訊(總索引)](http://data.taipei/opendata/datalist/datasetMeta?oid=d384ad18-1d77-4475-aa2a-34aa8fadafad)

**Comment by RexYuan** [comment]
@wi1d5ky 話說[臺北市政府資料開放平台](http://data.taipei/)的網址跟設計都好潮喔...

**Comment by wildskyf** [comment]
這個潮度有爆表！！！

**Comment by RexYuan** [comment]
雖然是可以直接上 5284 去 scrape 公車資訊要合法取得好像還要申請介接...
我看算了 這次即時資訊就先弄 YouBike 就好 可能頂多連結到 5284

**Comment by wildskyf** [comment]
居然還要申請，太麻煩了吧

**Comment by RexYuan** [comment]
真的[很煩](http://www.dot.taipei.gov.tw/ct.asp?xItem=3167481&CtNode=44829&mp=117001)
