### ISSUE TITLE
校車時間表在禮拜三要把 12:30 移除

### ISSUE THREAD

**Issue by wildskyf** [communityNTNU/surviveNTNU#19]

**Comment by RexYuan** [comment]
如果有可以移除的 script 可以直接加在 bus.coffee 的判斷星期然後計算的裡面

**Comment by wildskyf** [comment]
其實就直接加一個判斷在 bus.coffee 的最後面，如果當天是星期三就把表格的某格換掉
而那個某格可以直接給它一個叫做 "change" 的 class 或是 id 這樣要抓元素也比較輕鬆
