### ISSUE TITLE
網站與wiki目前差異

### ISSUE THREAD

**Issue by WilliamSnail** [communityNTNU/surviveNTNU#21]
## 只有在網站上

教室(這裡只有寫教室位置)

運動場地租借
## 只有在wiki上

交通資訊

場地租借(租借方法)

**Comment by wi1d5ky** [comment]
@RexYuan
這些是 wiki 上面已經有了的資料嗎？說的話我等等把他們順便更新上去

**Comment by wildskyf** [comment]
其實我看不太懂這個 issue 在講甚麼@@

**Comment by RexYuan** [comment]
之前有些wiki的東西沒在網站上 我都放上去後就關了 其實接下來就以網站為主好了

**Comment by wildskyf** [comment]
我在想要不要網站有的東西 wiki 那邊就砍掉，這樣也比較清楚哪些還沒加

**Comment by RexYuan** [comment]
砍完了！
