### ISSUE TITLE
各頁面加上 Disqus

### ISSUE THREAD

**Issue by wildskyf** [communityNTNU/surviveNTNU#22]
這樣就可以讓使用者在下面聊天(？)、快速回報之類的～

**Comment by wildskyf** [comment]
https://commentit.io/
這個也是很有趣XD

**Comment by RexYuan** [comment]
還沒細看 但我印象中如果要host在gh上不能加plugin 我等等看一下

Wildsky Fann notifications@github.com 於 2015年10月6日 週二 上午11:10寫道：

**Comment by RexYuan** [comment]
我看了好像沒問題 這個看來真的很酷欸 搞不好 /Issue_board 也可以用到這個
