### ISSUE TITLE
圖書館影印機

### ISSUE THREAD

**Issue by wildskyf** [communityNTNU/surviveNTNU#23]
![p_20151018_183304](https://cloud.githubusercontent.com/assets/6042803/10563696/1ec749f2-75c7-11e5-846c-217c175a019f.jpg)

**Comment by RexYuan** [comment]
![圖片](http://i.imgur.com/wBDTqPk.jpg)

補充

**Comment by wildskyf** [comment]
不知為何，把你的 markdown 改成半形還是不能出現圖片
![test](http://i.imgur.com/wBDTqPk.jpg)

**Comment by RexYuan** [comment]
closed by 85795c7ec0f5ba64ee1c8107b5868d4a534ef1f6
