### ISSUE TITLE
常用連結放在 Nav Bar

### ISSUE THREAD

**Issue by wildskyf** [communityNTNU/surviveNTNU#24]
我覺得右上角的 Nav Bar 應該可以放這些連結！

**Comment by wildskyf** [comment]
或是 Footer？然後把 Footer 的連結丟上去

**Comment by wildskyf** [comment]
暫時放到下面去

**Comment by RexYuan** [comment]
這樣好看很多

**Comment by RexYuan** [comment]
不過有個問題 目前這樣手機版要拉很久

**Comment by wildskyf** [comment]
沒錯，所以我才想放到 nav bar 去，但這樣手機版的標題可能就要變小，右上角才能再加個 menu 之類的。

**Comment by RexYuan** [comment]
我有個想法 但不知道可能性多少 就是有沒有可能做出橫向的捲軸放這些icon?

**Comment by RexYuan** [comment]
不過這樣也可能連結一多要滑很久 navbar加burger似乎是比較聰明的辦法

**Comment by wildskyf** [comment]
我也比較 prefer 加 burger，或者就是像 http://gnumdk.github.io/lollypop-web/ 這樣，加在旁邊。

雖然我這個動畫做得有點醜XD

**Comment by RexYuan** [comment]
還有一個方法是讓這個常用連結區collapse

**Comment by wildskyf** [comment]
這樣手機版面還是會拉很長，放`你想尋求什麼協助？`的前面的話就跟 burger 的感覺差不多了

BTW, Pro Tip 那邊怎麼變這樣，
`<a id="protip">` 是為了什麼而加的？我只知道前面有說 id 要改而已XD

**Comment by RexYuan** [comment]
我剛好看到最新消息的位置感覺很適合就改了

你是指為什麼要anchor tag嗎？我是想說如果protip是某個reference的內容 可以連結過去 如果是活動快報等等 也可以連過去

**Comment by RexYuan** [comment]
那就之後先改像是你在lollipop 做的或是burger這種類型的ㄅ

**Comment by wildskyf** [comment]
我想一下怎麼做最合風格

**Comment by RexYuan** [comment]
@wi1d5ky 我想到為什麼我會說PROTIP要替換 anchor tag 了 因為如果那邊不放連結的話style出不來（然後我不知道怎麼改） 我是想說如果真的需要連結的時候可以再想別的辦法加 像是我現在的三個是這樣

``` JavaScript
protips = [
    '如果不想被當成新手，師大路口綠燈時別急著走！',
    '師大路口水果店的綜合果汁第二杯半價可寄杯！',
    '<a href="https://livehouse.in/channel/365461/record/-K3V6D4UUmEPYevkVI_R">錯過了啦啦？到師青看重播！</a>'
]
```

**Comment by wildskyf** [comment]
我週末有空的話再來改！

Chih-cheng Yuan notifications@github.com 於 2015年11月26日 週四 下午10:55寫道：

**Comment by wi1d5ky** [comment]
決定就用這個了，我有空的時候來弄
http://www.sitepoint.com/pure-css-off-screen-navigation-menu/

**Comment by wildskyf** [comment]
@RexYuan 總覺得常用連結說不定會越來越多，所以這個還是作罷。

我個人希望整個網站重新設計，不過這就另開個新 issue 了(Ref: #56)。

這邊就先 close 吧！
