### ISSUE TITLE
FB 部分擴充

### ISSUE THREAD

**Issue by RexYuan** [communityNTNU/surviveNTNU#28]
要加上如靠北版等等相關的社群網站等資料

**Comment by wildskyf** [comment]
我覺得這個可以獨立出來耶
必要的、找不到的再放進來

**Comment by RexYuan** [comment]
我覺得有道理 但擔心這樣早成誤解 可能名字要之後區分的一下

**Comment by wildskyf** [comment]
什麼資訊牆之類的…
我在想可以讓使用者註冊，就能夠自選要哪些社團/粉專的內容出現
而沒有註冊的使用者預設就是載入所有的（但這樣我在想會有效能問題…

**Comment by wildskyf** [comment]
因為最近幫資訊社接 Facebook API 有感，覺得不用浪費時間在這種事情上了…
他們的接口會一直改，然後最後你什麼東西都拿不到…
如果要浪費時間維護這堆牆還不如去開發其他的更有趣些～XD
