### ISSUE TITLE
學校 WIFI 怎麼連教學

### ISSUE THREAD

**Issue by RexYuan** [communityNTNU/surviveNTNU#29]
5G 是什麼？guest 是什麼？TANet 又是什麼？我是 vip 嗎？

**Comment by WilliamSnail** [comment]
那些是學校的Wifi名稱，學生可以連那些?朋友不是師大生來也可以連嗎?

師大所提供之Wifi名稱一覽表:

#學生、教職員可使用
1.ntnu：提供予全校教職員生連結使用，須通過身分認證後方可使用(頻段2.4Ghz)。

2.NTNU-5G：由於無線網路常用之 2.4GHz 頻段之頻道數有限，且易遭周邊無線設備、電器設備等干擾而導致無線網路品質不穩定（不干擾頻道僅有 1、6、11 三個頻道），為了改善此問題，資中在校本部及公館校區大部分區域皆已提供 5GHz 頻道無線網路服務，若手持行動裝置或是筆電可支援 5GHz 無線上網，可優先選擇連線 SSID 為 NTNU-5G 之基地台。

##所有人皆可使用
3.ntnu_guest：為便民而提供予訪客使用的免費無線上網服務。可讓來師大的校外訪客不必申請帳號密碼，直接透過本校提供之無線網路服務，惟瞬間最大存取流量限制為 1MB，使用時連上此Wifi並使用瀏覽器同意條款後登入。

###通過申請後可使用
4.ntnu_vip：以綁定上網設備的無線網卡 MAC Address 之方式進行開通，開通後無需認證即可直接使用，所有存取權限及所享有的無線網路資源與連接 ntnu 相同，現僅開放予各行政主管視需求提出申請始開通使用，方便各主管於開會時能快速取得會議資料。

5.TANetRoaming：為達成教育部所期望促使臺灣學術網路無線漫遊互聯及共用之目的所開設，可讓臺灣學術網路無線漫遊成員之教職員生到師大時可直覺連結。104年8月 TANetRoaming 業已開通使用 iTaiwan 帳號連線。請於帳號部份輸入您的 iTaiwan 帳號加上 @itw，舉例來說如：0912345678@itw，並輸入密碼後即可登入使用。

**Comment by WilliamSnail** [comment]
資料來源: http://www.itc.ntnu.edu.tw/page1/super_pages.php?ID=page101&Sn=3

重要提醒：
 上述五個 SSID 乃是由同一顆無線基地台所發出並提供服務，故其無線網路資源為共享，包括無線基地台同時間所能承載的連線數以及對外頻寬( 雖然 ntnu_guest 之使用者有 1MB 頻寬使用限制，但當連結之使用者一多時也將占用到頻寬 )。

**Comment by RexYuan** [comment]
大哥 除了直接拿資中的解釋 可不可以加上點白話文 不然我也不懂他們在說什麼 更別說一般同學
能不能用簡單的中文講一下什麼情況要用什麼就好？

**Comment by wildskyf** [comment]
提供一個連到該頁的連結，然後我們的頁面就用我們自己的解釋就好

**Comment by wildskyf** [comment]
然後 markdown 的標題記得 # 後面要空一格

**Comment by wildskyf** [comment]
「1.」「2.」後面也要空一格
詳情可以參考 http://markdown.tw

**Comment by wildskyf** [comment]
話說 NTNU-5G 就是高級設備的 wifi，我的手機和電腦都收不到 :-$

**Comment by wildskyf** [comment]
vip 的話上面是說只有主任級的人可以用，簡單的說就是高官大官專用。

**Comment by wildskyf** [comment]
TANetRoaming 就是外校好友來到可以 try try 看

**Comment by WilliamSnail** [comment]
此篇已在 comment  78784cb85e7f22820f1373ad67ce5b02d8b8b588 內完成

**Comment by jaidTw** [comment]
說5G是高階版其實不太恰當，其實就是另外一種選擇，只是因為目前支援5G的設備還不普及，使用人數不多，所以該頻段的干擾相較主流的2.4GHz之下少了些，「理論上」連線品質會好一點，日後如果5G使用者一多，品質未必會比2.4G好
