### ISSUE TITLE
Resize image

### ISSUE THREAD

**Issue by RexYuan** [communityNTNU/surviveNTNU#31]
目前圖片直接放上去會爆掉

![Uploading Screen Shot 2015-11-27 at 12.57.30 AM.png…]()
![screen shot 2015-11-27 at 12 57 34 am](https://cloud.githubusercontent.com/assets/5001650/11427946/dfa2a894-94a1-11e5-970c-a16b0247173d.png)

**Comment by wildskyf** [comment]
close #31 via 86cf901
