### ISSUE TITLE
404 依然 404

### ISSUE THREAD

**Issue by wildskyf** [communityNTNU/surviveNTNU#33]
我們的 404 頁面依然不是我們自訂的 404.html

![2015-11-27 09-58-11](https://cloud.githubusercontent.com/assets/6042803/11432639/78446628-94ed-11e5-99c3-1a0b066aa231.png)

**Comment by RexYuan** [comment]
我忘了我原本有開 [SmartErrors](https://www.cloudflare.com/apps/smarterrors/) 現在關掉應該正常了

![screen shot 2015-11-27 at 11 04 53 pm](https://cloud.githubusercontent.com/assets/5001650/11443825/49e10c50-955b-11e5-9a11-0f1b4da3c5db.png)
