### ISSUE TITLE
部份瀏覽器破版

### ISSUE THREAD

**Issue by wildskyf** [communityNTNU/surviveNTNU#37]
我都不知道該說些什麼了…

ASUS Zenfone 5 內建瀏覽器：
<img src="https://cloud.githubusercontent.com/assets/6042803/11866610/35494852-a4e7-11e5-9b60-2e40e5283f7c.jpg" width="300">

ASUS Zenfone 2 內建瀏覽器：
<img src="https://cloud.githubusercontent.com/assets/6042803/11867141/24dc5394-a4ea-11e5-83e7-10c4105e1cf0.jpg" width="300">

safari on iPad mini 2：
<img src="https://cloud.githubusercontent.com/assets/6042803/11866827/6d7a8e88-a4e8-11e5-929a-9f09a7f6811c.jpg" width="500">

**Comment by wildskyf** [comment]
http://caniuse.com/#search=%3D%3E
原來是 safari 不支援 arrow function…

**Comment by RexYuan** [comment]
Safari :wheelchair:
![screen shot 2015-12-17 at 7 02 21 pm](https://cloud.githubusercontent.com/assets/5001650/11868135/ba663d0c-a4f0-11e5-9d54-cb4db4472c2e.png)

**Comment by wildskyf** [comment]
該面對的還是要面對，來修 RWD 囉

**Comment by wildskyf** [comment]
table 的 RWD 真是令人頭痛

**Comment by wildskyf** [comment]
不想修了XD
本網站只支援 modern browser!!
