### ISSUE TITLE
Protip: 天氣

### ISSUE THREAD

**Issue by RexYuan** [communityNTNU/surviveNTNU#42]
好冷

**Comment by wildskyf** [comment]
這個不用吧XDD

**Comment by RexYuan** [comment]
我是想說可以動態加入「今天晚上會很冷喔」「等等可能會下雨」

**Comment by RexYuan** [comment]
http://openweathermap.org/api

**Comment by wildskyf** [comment]
sounds great！

Chih-cheng Yuan notifications@github.com 於 2015/12/18週五 12:56 寫道：
