### ISSUE TITLE
Icon License

### ISSUE THREAD

**Issue by wildskyf** [communityNTNU/surviveNTNU#43]
我們現在使用的 icon 都是我從 http://www.flaticon.com/ 這個網站拿來的。
目前只是隨便找，希望可以找一個取代它的方案，因為使用這個網站的 icon 的話我們有必要 take credit for theme （在網站中給一個連結到這個網站的 Link 之類的動作）
其實放一下也不是不行，只是我一時想不到要放哪裡XD

**Comment by RexYuan** [comment]
[他們說](http://support.flaticon.com/hc/en-us/articles/202798381-How-do-I-insert-correctly-the-attribution)：

> For websites: 
> Insert the attribution on the page of the icon (for example in the page footer) or on the imprint page.

我先放在 /humans.txt 裡面，要是不行的話再改

不過我找了一下，發現大部分網路上的 icon 不用 attribution 的大都很醜或很少...
