### ISSUE TITLE
Footer 字太多

### ISSUE THREAD

**Issue by wildskyf** [communityNTNU/surviveNTNU#5]
![screenshot from 2015-09-03 00-47-01](https://cloud.githubusercontent.com/assets/6042803/9637784/52d7bd32-51d5-11e5-8803-7c1939f78c5e.png)

字太多了啦XDD
感覺不舒服，我打算把他獨立出來成另一個頁面！

footer 應該可以放一些其他的連結，像是：
緣起、開 issue、關於我們、加入我們、Facebook 粉專、代辦事項…之類的。

**Comment by RexYuan** [comment]
放 Facebook 圖示跟 GitHub 圖示，然後旁邊這三個如何？
「關於」、「回報問題」、「加入」

**Comment by wildskyf** [comment]
good！

Wildsky

-------- 原始郵件 --------
寄件者：RexYuan notifications@github.com
傳送日期：Thu, 03 Sep 2015 13:45:00 +0800
收件者：communityNTNU/surviveNTNU surviveNTNU@noreply.github.com
副本：wildsky poppin.wildsky@gmail.com
主旨:Re: [surviveNTNU] Footer 字太多 (#5)

**Comment by RexYuan** [comment]
認為應該區分 把部分東西移到 header
