### ISSUE TITLE
其他運動場地資訊

### ISSUE THREAD

**Issue by RexYuan** [communityNTNU/surviveNTNU#6]
運動場地租借頁面應改為 => 應包含桌球室開放時間、健身方開放時間等與使用方法

**Comment by wildskyf** [comment]
這個 issue 是指要在 wiki 裡面新增與`運動場地租借`相關的文件嗎?

**Comment by RexYuan** [comment]
是指要把健身房資訊 游泳池等加進來 就是不只放租借消息 我好像忘了寫內容了...

**Comment by RexYuan** [comment]
資訊一下太多可能雜 一個一個來好了 目前我有去重訓的時候順便記一下在 #53
