### ISSUE TITLE
背景圖 loading 太久了

### ISSUE THREAD

**Issue by wildskyf** [communityNTNU/surviveNTNU#7]
網速慢的使用者就完全看不到了，看要把現在的圖片壓縮或是想個方法讓它讀取更快速

**Comment by RexYuan** [comment]
[有這種東西](https://tinyjpg.com/):scream::scream::scream:

**Comment by wildskyf** [comment]
Jekyll 好像還有專門壓縮圖片的 plugin XDD
2015/9/16 下午9:38於 "RexYuan" notifications@github.com寫道：
