### ISSUE TITLE
https

### ISSUE THREAD

**Issue by wildskyf** [communityNTNU/surviveNTNU#75]

**Comment by RexYuan** [comment]
done

**Comment by wildskyf** [comment]
哇靠，我想說要來做做看就被你做掉了XDDD

**Comment by RexYuan** [comment]
其實原本就有，只是沒有把 http redirect 到 https。我是用 CloudFlare 的 DNS，他有免費的 Certificate，redirect 也只要按一個鈕而已ㄏ

**Comment by wildskyf** [comment]
XDDD

**Comment by wildskyf** [comment]
這樣很好啊，Easy things should be easy, and hard things should be possible.
