### ISSUE TITLE
校車表更新

### ISSUE THREAD

**Issue by wildskyf** [communityNTNU/surviveNTNU#8]
校車與三校專車整併，須更新該頁資訊。
### 相關網址
- http://www.ga.ntnu.edu.tw/bus.html
- http://triangle.ntu.edu.tw/traffic.html

**Comment by WilliamSnail** [comment]
三校專車計畫一開始即整併了，頁面 「交通資訊」裡即是整併後的時間表，不過並未放在網頁的「校車時間」區域。

**Comment by RexYuan** [comment]
@WilliamSnail 這學期校車時刻有改變，你能不能更新一下

**Comment by WilliamSnail** [comment]
變化為8:30車班改為8:50
已經修改完成

**Comment by RexYuan** [comment]
變化不只那個吧⋯⋯

**Comment by wildskyf** [comment]
剛剛收到學校信件了
![交通車更新表](https://cloud.githubusercontent.com/assets/6042803/9897101/32cd8e02-5c77-11e5-8463-14dbd57758dc.jpg)

**Comment by WilliamSnail** [comment]
昨天就更新完了喔

**Comment by RexYuan** [comment]
剛已經更新了[Wiki](https://github.com/communityNTNU/surviveNTNU/wiki/%E4%BA%A4%E9%80%9A%E8%B3%87%E8%A8%8A)並在 163a1f9a76b9c0ae7e2eab32467a4265b73a53b9 更新顯示的時刻表，但是[提示](https://github.com/communityNTNU/surviveNTNU/commit/163a1f9a76b9c0ae7e2eab32467a4265b73a53b9#diff-defb1cedd6eadaae1d08a3004cfe1456R26)的部分我看不是很懂 :sob: @wi1d5ky 你可能得檢查一下

**Comment by RexYuan** [comment]
![screen shot 2015-09-19 at 6 00 07 pm](https://cloud.githubusercontent.com/assets/5001650/9975693/4d746d06-5ef8-11e5-8452-9b18c66e307a.png)
:hammer:

**Comment by wildskyf** [comment]
什麼提示？你是指告訴使用者下一班車還要多久的那個嗎？

**Comment by wildskyf** [comment]
本部提示已更新，公館校區我有空再補。

**Comment by RexYuan** [comment]
:smile_cat: Thanks!

wildsky notifications@github.com 於 2015年9月19日 週六 下午10:48寫道：

**Comment by wildskyf** [comment]
奇怪，今天的公館的車，12:20 就發車了

**Comment by RexYuan** [comment]
司機是否還沒更新 :smirk:

**Comment by RexYuan** [comment]
d4d1adb233fde9c71b50ec12775804bdd2c9ac79
